//go:build ignore

// Command gen_chrome writes the trust_anchors (0xca34) capture from the
// Chrome Root Store that Google ships to browsers.
//
// The store travels in the PKI Metadata component. This command asks Omaha for
// it, downloads the CRX3, and reads crs.pb, a chrome_root_store.RootStore. It
// keeps the trust_anchor_id of every trust_anchors entry, and of an
// additional_certs entry only with tls_trust_anchor: true.
//
// Run "go generate ./trust_anchors".
//
// Flags:
//
//	-out     file to write. A test compares a fresh list with the committed one.
//	-source  read a local crs.pb instead of Omaha, for a test without a network.
//
// The header of the generated file records the component version, the digest of
// the package, the store version, and the anchor count.
package main

import (
	"archive/zip"
	"bytes"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/binary"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"log"
	mrand "math/rand/v2"
	"net/http"
	"net/url"
	"os"
	"strings"
	"time"
)

const defaultOutputPath = "chrome_generated.go"

// pkiMetadataAppID is the component that carries crs.pb.
// https://chromium.googlesource.com/chromium/src/+/main/chrome/browser/component_updater/pki_metadata_component_installer.cc
const pkiMetadataAppID = "efniojlnjndmcbiieegkicadnoecjjef"

const omahaURL = "https://update.googleapis.com/service/update2/json"

// client gives every request of this command a deadline.
var client = &http.Client{Timeout: 2 * time.Minute}

// chromiumDashURL lists the recent stable Chrome for Android builds, newest
// first.
const chromiumDashURL = "https://chromiumdash.appspot.com/fetch_releases?channel=Stable&platform=Android&num=10"

// stableChromeVersion picks one recent stable Chrome for Android build at
// random. The probe presents it to Omaha.
func stableChromeVersion() (string, error) {
	body, err := get(chromiumDashURL, 0, "")
	if err != nil {
		return "", err
	}

	var releases []struct {
		Version string `json:"version"`
	}

	if err := json.Unmarshal(body, &releases); err != nil {
		return "", fmt.Errorf("%s: %w", chromiumDashURL, err)
	}

	if len(releases) == 0 {
		return "", fmt.Errorf("%s: the answer holds no release", chromiumDashURL)
	}

	return releases[mrand.IntN(len(releases))].Version, nil
}

func main() {
	out := flag.String("out", defaultOutputPath, "file to write")
	local := flag.String("source", "", "read a local crs.pb instead of Omaha, for a test")
	flag.Parse()

	var (
		store     []byte
		component = "local"
	)

	if *local != "" {
		body, err := os.ReadFile(*local)
		if err != nil {
			log.Fatal(err)
		}

		store = body
	} else {
		chrome, err := stableChromeVersion()
		if err != nil {
			log.Fatal(err)
		}

		fmt.Printf("the probe presents Chrome %s\n", chrome)

		crx, err := pkiMetadataComponent(chrome)
		if err != nil {
			log.Fatal(err)
		}

		component = crx.version

		store, err = crxFile(crx.body, "crs.pb")
		if err != nil {
			log.Fatal(err)
		}
	}

	ids, version, err := parse(store)
	if err != nil {
		log.Fatal(err)
	}

	digest := fmt.Sprintf("%x", sha256.Sum256(store))

	var list strings.Builder

	for _, id := range ids {
		// An 8-bit record length and a 16-bit list length hold no more.
		if len(id) > 255 {
			log.Fatalf("a trust anchor ID of %d bytes fits no record", len(id))
		}

		list.WriteString(fmt.Sprintf("%02x%x", len(id), id))
	}

	if list.Len()/2 > 65535 {
		log.Fatalf("a list of %d bytes fits no payload", list.Len()/2)
	}

	capture := fmt.Sprintf("%04x%s", list.Len()/2, list.String())

	source := fmt.Sprintf(`// Code generated by gen_chrome.go. DO NOT EDIT.
// Source: crs.pb of the PKI Metadata component %s
// Component: %s
// SHA-256: %s
// Chrome Root Store version: %d
// Anchors: %d

package trust_anchors

const chromeCapture = %q
`, pkiMetadataAppID, component, digest, version, len(ids), capture)

	if err := os.WriteFile(*out, []byte(source), 0o644); err != nil {
		log.Fatal(err)
	}

	fmt.Printf("wrote %s with %d anchors from store version %d, component %s\n", *out, len(ids), version, component)
}

// component is one release of the PKI Metadata component.
type component struct {
	version string
	digest  string
	body    []byte
}

// pkiMetadataComponent asks Omaha for the component and downloads it. The
// request uses protocol 3.1, and testsource keeps the probe out of the normal
// update counts.
func pkiMetadataComponent(chrome string) (component, error) {
	id := func() string { return "{" + uuid() + "}" }

	body, err := json.Marshal(map[string]any{"request": map[string]any{
		"protocol": "3.1", "dedup": "cr", "acceptformat": "crx3",
		"updater": "chrome", "updaterversion": chrome, "prodversion": chrome,
		"os":   map[string]any{"platform": "Android", "version": "16", "arch": "x86_64"},
		"arch": "x64", "testsource": "crs-monitor", "sessionid": id(), "requestid": id(),
		"app": []any{map[string]any{
			"appid": pkiMetadataAppID, "version": "0.0.0.0",
			"installsource": "ondemand", "updatecheck": map[string]any{},
		}},
	}})
	if err != nil {
		return component{}, err
	}

	// Omaha checks the request against cup2hreq, so it must see these bytes.
	nonce := make([]byte, 32)
	if _, err := rand.Read(nonce); err != nil {
		return component{}, err
	}

	query := url.Values{
		"cup2key":  {"11:" + base64.RawURLEncoding.EncodeToString(nonce)},
		"cup2hreq": {fmt.Sprintf("%x", sha256.Sum256(body))},
	}

	resp, err := client.Post(omahaURL+"?"+query.Encode(), "application/json", bytes.NewReader(body))
	if err != nil {
		return component{}, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return component{}, fmt.Errorf("%s: status %d", omahaURL, resp.StatusCode)
	}

	answer, err := io.ReadAll(resp.Body)
	if err != nil {
		return component{}, err
	}

	// Omaha writes ")]}'" before the JSON to break script inclusion.
	if rest, found := strings.CutPrefix(string(answer), ")]}'"); found {
		answer = []byte(rest)
	}

	var update struct {
		Response struct {
			App []struct {
				UpdateCheck struct {
					Status string `json:"status"`
					URLs   struct {
						URL []struct {
							Codebase string `json:"codebase"`
						} `json:"url"`
					} `json:"urls"`
					Manifest struct {
						Version  string `json:"version"`
						Packages struct {
							Package []struct {
								Name string `json:"name"`
								Size int64  `json:"size"`
								Hash string `json:"hash_sha256"`
							} `json:"package"`
						} `json:"packages"`
					} `json:"manifest"`
				} `json:"updatecheck"`
			} `json:"app"`
		} `json:"response"`
	}

	if err := json.Unmarshal(answer, &update); err != nil {
		return component{}, fmt.Errorf("%s: %w", omahaURL, err)
	}

	if len(update.Response.App) == 0 {
		return component{}, fmt.Errorf("%s: the answer holds no app", omahaURL)
	}

	check := update.Response.App[0].UpdateCheck
	if check.Status != "ok" {
		return component{}, fmt.Errorf("%s: update status %q", omahaURL, check.Status)
	}

	if len(check.Manifest.Packages.Package) == 0 {
		return component{}, fmt.Errorf("%s: the answer holds no package", omahaURL)
	}

	pkg := check.Manifest.Packages.Package[0]

	var failures []string

	for _, item := range check.URLs.URL {
		if !strings.HasPrefix(item.Codebase, "https://") {
			continue
		}

		body, err := get(item.Codebase+pkg.Name, pkg.Size, pkg.Hash)
		if err != nil {
			failures = append(failures, err.Error())
			continue
		}

		return component{check.Manifest.Version, strings.ToLower(pkg.Hash), body}, nil
	}

	return component{}, fmt.Errorf("no https download of %s answered: %s", pkg.Name, strings.Join(failures, "; "))
}

// get reads a URL. A size above zero and a digest are checked against the body.
func get(url string, size int64, digest string) ([]byte, error) {
	resp, err := client.Get(url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("%s: status %d", url, resp.StatusCode)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}

	if size > 0 && int64(len(body)) != size {
		return nil, fmt.Errorf("%s: %d bytes, the manifest says %d", url, len(body), size)
	}

	if got := fmt.Sprintf("%x", sha256.Sum256(body)); digest != "" && !strings.EqualFold(got, digest) {
		return nil, fmt.Errorf("%s: digest %s, the manifest says %s", url, got, digest)
	}

	return body, nil
}

// crxFile returns one file of a CRX3 archive. A CRX3 holds "Cr24", the version
// 3, the length of a protobuf header, that header, and then a ZIP.
// https://chromium.googlesource.com/chromium/src/+/main/components/crx_file/crx3.proto
func crxFile(crx []byte, name string) ([]byte, error) {
	if len(crx) < 12 || string(crx[:4]) != "Cr24" {
		return nil, errors.New("the download is not a CRX file")
	}

	if version := binary.LittleEndian.Uint32(crx[4:8]); version != 3 {
		return nil, fmt.Errorf("the download is CRX version %d, expected 3", version)
	}

	offset := 12 + int(binary.LittleEndian.Uint32(crx[8:12]))
	if offset >= len(crx) {
		return nil, errors.New("the CRX header length runs past the end")
	}

	archive, err := zip.NewReader(bytes.NewReader(crx[offset:]), int64(len(crx)-offset))
	if err != nil {
		return nil, err
	}

	file, err := archive.Open(name)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	return io.ReadAll(file)
}

// Field numbers of chrome_root_store.RootStore and TrustAnchor.
// https://chromium.googlesource.com/chromium/src/+/main/net/cert/root_store.proto
const (
	rootStoreTrustAnchors   = 1
	rootStoreVersionMajor   = 2
	rootStoreAdditionalCert = 3

	anchorTLSTrustAnchor = 10
	anchorTrustAnchorID  = 11
)

// parse returns the trust anchor IDs a browser advertises and the store version.
// Every trust_anchors entry is a TLS anchor. An additional_certs entry is one
// only with tls_trust_anchor: true.
func parse(store []byte) ([][]byte, int64, error) {
	var (
		ids     [][]byte
		version int64
	)

	err := walk(store, func(field, kind int, value []byte, number uint64) error {
		switch {
		case field == rootStoreVersionMajor && kind == 0:
			version = int64(number)
		case field == rootStoreTrustAnchors && kind == 2:
			id, _, err := anchor(value)
			if err != nil || len(id) == 0 {
				return err
			}

			ids = append(ids, id)
		case field == rootStoreAdditionalCert && kind == 2:
			id, trusted, err := anchor(value)
			if err != nil || len(id) == 0 || !trusted {
				return err
			}

			ids = append(ids, id)
		}

		return nil
	})
	if err != nil {
		return nil, 0, err
	}

	if version == 0 || len(ids) == 0 {
		return nil, 0, fmt.Errorf("crs.pb gives version %d and %d anchor IDs", version, len(ids))
	}

	return ids, version, nil
}

// anchor returns the ID of one TrustAnchor and whether it is a TLS anchor.
func anchor(message []byte) ([]byte, bool, error) {
	var (
		id      []byte
		trusted bool
	)

	err := walk(message, func(field, kind int, value []byte, number uint64) error {
		switch {
		case field == anchorTrustAnchorID && kind == 2:
			id = value
		case field == anchorTLSTrustAnchor && kind == 0:
			trusted = number != 0
		}

		return nil
	})

	return id, trusted, err
}

// walk reads the fields of a protobuf message and visits the varint and the
// length delimited ones, which are the only types a caller here reads.
func walk(message []byte, visit func(field, kind int, value []byte, number uint64) error) error {
	for at := 0; at < len(message); {
		key, next, err := varint(message, at)
		if err != nil {
			return err
		}

		at = next
		field, kind := int(key>>3), int(key&7)

		switch kind {
		case 0:
			number, next, err := varint(message, at)
			if err != nil {
				return err
			}

			at = next

			err = visit(field, kind, nil, number)
			if err != nil {
				return err
			}
		case 2:
			length, next, err := varint(message, at)
			if err != nil {
				return err
			}

			if length > uint64(len(message)-next) {
				return errors.New("a length delimited field is truncated")
			}

			at = next + int(length)

			err = visit(field, kind, message[next:at], 0)
			if err != nil {
				return err
			}
		case 1:
			at += 8
		case 5:
			at += 4
		default:
			return fmt.Errorf("wire type %d is unknown", kind)
		}

		if at > len(message) {
			return errors.New("a field is truncated")
		}
	}

	return nil
}

// varint reads one protobuf varint and returns the position after it.
func varint(data []byte, at int) (uint64, int, error) {
	var value uint64

	for shift := 0; shift < 70; shift += 7 {
		if at >= len(data) {
			return 0, 0, errors.New("the varint is truncated")
		}

		b := data[at]
		at++
		value |= uint64(b&0x7f) << shift

		if b&0x80 == 0 {
			return value, at, nil
		}
	}

	return 0, 0, errors.New("the varint is too long")
}

// uuid returns a random UUID version 4. Omaha wants one per session and request.
func uuid() string {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		panic(err)
	}

	b[6] = b[6]&0x0f | 0x40
	b[8] = b[8]&0x3f | 0x80

	return fmt.Sprintf("%x-%x-%x-%x-%x", b[0:4], b[4:6], b[6:8], b[8:10], b[10:16])
}
